services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: fpgrowth-backend:latest
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - "D:/Documents/My Project/FP-Growth_mba/backend:/app/backend"
      - "D:/Documents/My Project/FP-Growth_mba/fp_growth_mba:/app/fp_growth_mba"
      - "D:/Documents/My Project/FP-Growth_mba/data:/app/data"
      - "D:/Documents/My Project/FP-Growth_mba/models:/app/models"
      - "D:/Documents/My Project/FP-Growth_mba/docker/profiles.yml:/root/.dbt/profiles.yml"
    environment:
      - PYTHONPATH=/app
    entrypoint: ["tail", " -f", "/dev/null"] 
  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    image: fpgrowth-ui:latest
    container_name: ui-container
    ports:
      - "8501:8501"
    volumes:
      - "D:/Documents/My Project/FP-Growth_mba/ui:/app/ui"
    depends_on:
      - backend
