services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: fpgrowth-backend:latest
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend        
      - ../fp_growth_mba:/app/fp_growth_mba
      - ../data:/app/data
      - ../models:/app/models           
      - ./profiles.yml:/root/.dbt/profiles.yml
    environment:
      - PYTHONPATH=/app 

  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    image: fpgrowth-ui:latest
    container_name: ui-container
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ../ui:/app/ui
    depends_on:
      - backend
