version: 2

models:
  - name: stg_online_retail
    columns:
      - name: CustomerID
      - name: InvoiceNo
        tests:
          - not_null
      - name: StockCode
        tests:
          - not_null
      - name: Quantity
        tests:
          - not_null

  - name: dl_input
    columns:
      - name: user_id
        tests:
          - not_null
      - name: item_id
        tests:
          - not_null

  - name: fpgrowth_input
    columns:
      - name: InvoiceNo
        tests:
          - not_null
          - unique
      - name: products
        tests:
          - not_null

  - name: products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique 